Documented rules regards bivalent vaccinations
ehn-dcc-development/eu-dcc-overview pull request #22
Opened 2022-09-26 11:35 UTC by ryanbnl

2022-09-26 11:40 UTC, dslmeinte requested changes

2022-09-26 11:40 UTC, dslmeinte commented on faq/create-a-valid-dcc-payload.md
> +In late 2022 a number of bivalent vaccination subtypes have come on to the market. A number of these vaccines have received market approval for use within the EU. The approval is an extention of the
"extension"

2022-09-26 11:40 UTC, dslmeinte commented on faq/create-a-valid-dcc-payload.md
> +Base on the feedback received from the Health Security Committee the European Commission has decided that the bivalent vaccinations will be encoded within the DCC using the existing encoding of their
"Based"

2022-09-26 11:40 UTC, dslmeinte commented on faq/create-a-valid-dcc-payload.md
> +That means, for example, that if a person receives, as his or her second booster following a two-dose primary series, a dose of Comirnaty bivalent Original/Omicron BA.4/5, he or she should receive an
All "he or she" -> "they"?

2022-09-27 06:01 UTC, skounis approved these changes

2022-09-27 08:42 UTC, merged